/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: JMGameDev (https://sketchfab.com/JMGameDev)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/pokemon-basic-pokeball-9b29539199c14ddea4de7776c4d758df
title: Pokemon Basic Pokeball
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Pokeball(props) {
  const { nodes, materials } = useGLTF("/pokeball.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={0.025}>
            <mesh
              geometry={nodes.PokeBall__0.geometry}
              material={materials["Scene_-_Root"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/pokeball.gltf");
